name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  wait-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 60 minutes
        run: sleep 3600
